In [3]:
import pytorch_lightning as pl
import typing as th
import os

#count the number of cpu workers
num_workers = os.cpu_count()
print(num_workers)

8


In [1]:
# Create a permutation tensor from a permutation list
import torch

perm = [0, 2, 2]

n = len(perm)
assert set(perm) == set(range(n)), "perm must be a permutation of [0, 1, ..., n-1]"

inputs = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.float32)

P = torch.zeros((n, n))
P[torch.arange(n), perm] = 1
perm = P 
P = P.to(inputs.device)
P = P.type(inputs.dtype)
print(P)

AssertionError: perm must be a permutation of [0, 1, ..., n-1]

In [14]:
in_cov_features = [1, 2, 3]
out_cov_features = [6, 4, 2]
mask = torch.Tensor([[1, 0, 0],
                     [0, 1, 1],
                     [1, 1, 0]])
mask = torch.repeat_interleave(mask, torch.tensor(in_cov_features), dim=1)
mask = torch.repeat_interleave(mask, torch.tensor(out_cov_features), dim=0)
mask

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 1.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])

In [3]:
%load_ext autoreload

In [7]:
%autoreload 2
from ocd.models.order_discovery import SinkhornOrderDiscovery
import torch

batch_size = 10
cov_in = [3, 4, 2, 3]
# generate a random one-hot vector of size k = 3
x = torch.zeros(batch_size, sum(cov_in))
cummul = 0
for cat_sz in cov_in:
    x[torch.arange(batch_size), cummul + torch.randint(0, cat_sz, (batch_size,))] = 1
    cummul += cat_sz

model = SinkhornOrderDiscovery(
    in_covariate_features=cov_in,
    hidden_features_per_covariate=[[10, 20, 30, 10],
                                   [20, 30, 10, 5],
                                   [40, 30, 10, 7]],
    bias=True,
    activation=torch.nn.ReLU,)

model(x)


Parameter containing:
tensor([[ 1.9321, -0.2592, -1.1750,  0.6710],
        [-2.6185,  0.9256,  1.5300,  0.6207],
        [ 0.1632, -0.8190, -0.8127, -0.2467],
        [-0.7536,  1.4659,  1.3000,  0.3614]], requires_grad=True)
tensor([[8.2183e-16, 2.1139e-02, 9.9544e-01, 9.7635e-05],
        [8.5280e-01, 2.7085e-12, 3.1882e-17, 2.8903e-09],
        [6.7860e-09, 9.7886e-01, 4.5614e-03, 1.6206e-01],
        [1.4720e-01, 2.6450e-07, 6.8929e-09, 8.3784e-01]],
       grad_fn=<DivBackward0>)


tensor([[0.2954, 0.2970, 0.4077, 0.2531, 0.2448, 0.2509, 0.2511, 0.4572, 0.5428,
         0.2179, 0.3579, 0.4242],
        [0.2656, 0.4169, 0.3174, 0.2531, 0.2448, 0.2509, 0.2511, 0.6560, 0.3440,
         0.3749, 0.2230, 0.4020],
        [0.3578, 0.4234, 0.2188, 0.2531, 0.2448, 0.2509, 0.2511, 0.5409, 0.4591,
         0.2425, 0.4613, 0.2962],
        [0.3300, 0.2620, 0.4080, 0.2531, 0.2448, 0.2509, 0.2511, 0.4950, 0.5050,
         0.2505, 0.3337, 0.4159],
        [0.4299, 0.3299, 0.2403, 0.2531, 0.2448, 0.2509, 0.2511, 0.3295, 0.6705,
         0.2711, 0.3667, 0.3622],
        [0.2954, 0.2970, 0.4077, 0.2531, 0.2448, 0.2509, 0.2511, 0.4572, 0.5428,
         0.2179, 0.3579, 0.4242],
        [0.3309, 0.2963, 0.3728, 0.2531, 0.2448, 0.2509, 0.2511, 0.6132, 0.3868,
         0.3949, 0.3698, 0.2352],
        [0.3484, 0.3791, 0.2726, 0.2531, 0.2448, 0.2509, 0.2511, 0.6254, 0.3746,
         0.2131, 0.4240, 0.3629],
        [0.2885, 0.4528, 0.2587, 0.2531, 0.2448, 0.2509, 0.2511, 0.3842, 0.6158,

In [1]:
import torch
batch_size = 10
cov_in = [3, 4, 2, 3]
# generate a random one-hot vector of size k = 3
x = torch.zeros(batch_size, sum(cov_in))
cummul = 0
for cat_sz in cov_in:
    x[torch.arange(batch_size), cummul + torch.randint(0, cat_sz, (batch_size,))] = 1
    cummul += cat_sz
x


tensor([[1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0.],
        [0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
        [1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.],
        [0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
        [1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.]])

In [44]:
%autoreload 2
from ocd.models.sinkhorn import sample_permutation_matrix

P = sample_permutation_matrix(torch.Tensor([[1, 0, 0],
                                        [0, 1, 10], 
                                        [1, 1, 0]]),
                                        n_samples=5, train=True, n_iter=10, tau=0.1)

print(P.sum(-1))

tensor([[1.0458, 0.9956, 0.9586],
        [1.0000, 1.0000, 1.0000],
        [1.0002, 0.9521, 1.0476],
        [0.9973, 0.9645, 1.0382],
        [1.0404, 0.9332, 1.0264]])


In [2]:
%load_ext autoreload

In [19]:
%autoreload 2

from ocd.models.made import SingleMaskedBlockMADE
# from ocd.models.utils import log_prob
from ocd.models.utils import log_prob

model = SingleMaskedBlockMADE(
    in_covariate_features=cov_in,
    hidden_features_per_covariate=[[10, 20, 30, 10],
                                   [20, 30, 10, 5],
                                   [40, 30, 10, 7]],
    bias=True,
    activation=torch.nn.ReLU,
)

probas = model(x, perm=[0, 1, 2, 3])
log_prob(probas, cov_in, categories=[[0, 2, 1, 2] for _ in range(x.shape[0])], reduce=True)


tensor([1.5829, 1.2029, 1.3771, 1.6821, 1.6871, 1.1648, 1.5599, 1.0990, 1.2029,
        1.1375], grad_fn=<SumBackward1>)